# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveSmallIntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('tags', models.CharField(choices=[('DEF', 'No Tag'), ('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('SN', 'Snack'), ('SUP', 'Supplement'), ('C', 'Cheat'), ('T', 'Tasty'), ('Y', 'Yuck!'), ('HC', 'High Calorie'), ('LC', 'Low Calorie')], default='DEF', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
