# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('calories', models.PositiveSmallIntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('tags', models.CharField(choices=[('DEF', 'No Tag'), ('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('SN', 'Snack'), ('SUP', 'Supplement'), ('C', 'Cheat'), ('T', 'Tasty'), ('Y', 'Yuck!'), ('HC', 'High Calorie'), ('LC', 'Low Calorie')], default='DEF', max_length=64)),
            ],
        ),
    ]
