# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_app', '0002_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
